### ISSUE TITLE
Incorrect objects passed to url helpers?

### ISSUE THREAD

**Issue by mileszs** [dcrec1/signal#4]
This makes little sense to me, but this is what I'm seeing. I am getting 500 errors when trying to setup a project for the first time. (I'm using Passenger on Ubuntu 9.10, ruby 1.8.7.) The errors are all related to not being able to figure out the correct path based on the project passed. In other words, it wants the plain 'id' instead of the full project object. When I switch from, say, project_url(project) to project_url(project.id), it works. 

Is there some bit of configuration, or conflicting libraries, or something, that I'm missing? I've decided to not go through a change all the routes (including form_for calls!). It really makes no sense, as Rails typically figures things out correctly. 

Any ideas?

**Comment by mileszs** [comment]
Perhaps I should be ignored. I re-cloned signal and started over. Things seem to be good.

**Comment by dcrec1** [comment]
Ok, cool :)
